### ISSUE TITLE
Why doesn't ReentrantMutex implement DerefMut?

### ISSUE THREAD

**Issue by ckaran** [Amanieu/parking_lot#121]
Reading through the [documentation](https://docs.rs/parking_lot/0.7.1/parking_lot/type.ReentrantMutex.html) for `ReentrantMutex`, I noticed that it explicitly does not implement `DerefMut`.  Why?  I know that there must be a good reason not to, but I honestly can't think of why.

**Comment by yvt** [comment]
I assume you meant `ReentrantMutexGuard` because mutexes themselves won't let you access the contents without explicit locking.

<https://docs.rs/lock_api/0.1.5/lock_api/struct.ReentrantMutex.html>:
> - `ReentrantMutexGuard` does not give mutable references to the locked data. Use a `RefCell` if you need this.

Consider the following example:

```rust
let mutex = ReentrantMutex::new(1);
let (mut lock1, mut lock2) = (mutex.lock(), mutex.lock());
// let (ref1, ref2) = (&mut *lock1, &mut *lock2); // `DerefMut` is not implemented for `ReentrantMutexGuard`
```

If `ReentrantMutexGuard` had implemented `DerefMut`, the third line would create two mutable references pointing the same location, triggering an undefined behavior.

**Comment by ckaran** [comment]
@yvt Got it!  Thank you for the beautiful explanation! It may be worth putting a note in the documentation about this.
