### ISSUE TITLE
Create a new release for crates.io

### ISSUE THREAD

**Issue by ckaran** [Amanieu/parking_lot#136]
@Amanieu can you please bump the version number and create a new release for `crates.io`?  Now that `parking_lot` supports `serde`, I want to clean up my `Cargo.toml` dependencies so that they are pointing to `crates.io` rather than github.

**Comment by Amanieu** [comment]
@faern Does #119 currently have any breaking changes? If not then we can just release now and just pin the submodule on a later commit.

**Comment by faern** [comment]
I don't think that PR is breaking. I skimmed it now and could not see anything. I think we already merged all breaking changes.

But I also created #137 after reading through the serde PR.

**Comment by faern** [comment]
Would be good to get a new version out to crates.io. A lot of things improved since `0.7.1` already, and no one knows when this will be merged to libstd anyway. Some prominent improvements include:
* Support for new platforms: wasm, SGX, Redox, CloudABI.
* The bug around `was_last_thread` has been fixed.
* Making more stuff const fns on stable Rust
* Smaller smaller locking primitives and futex based thread parker on stable Rust thanks to `AtomicU8`.
* ... And more...

Only thing I can of that we might possibly want to backport from #119 to master before a release is the change where SGX aborts instead of panics 🤷‍♂

**Comment by Amanieu** [comment]
I just published new versions of all 3 crates.
