### ISSUE TITLE
Question: GuardNoSend vs GuardSend

### ISSUE THREAD

**Issue by mtak-** [Amanieu/parking_lot#139]
I notice both `RawMutex` and `RawRwLock` use `GuardNoSend`, while the spinlock in the `lock_api` documentation uses `GuardSend`. What prevents `RawMutex`/`RawRwLock` guards from being `Send`?

**Comment by Amanieu** [comment]
The deadlock detection code (which can be enabled through a feature) will break if a mutex can be unlocked in a different thread than the one that locked it. It was decided that disabling `MutexGuard: Send` if that feature is enabled would be unacceptable since it might break code that relies on `MutexGuard: Send`.

**Comment by mtak-** [comment]
Thanks you! That makes a lot of sense.
