### ISSUE TITLE
Switch from owning_ref to stable_deref_trait

### ISSUE THREAD

**Issue by Storyyeller** [Amanieu/parking_lot#25]
Hi, I noticed that you have an optional dependency on owning_ref in order to implement StableAddress for your custom mutex guard types. Starting with version 0.3.3 of owning_ref, this trait has been refactored into [a separate crate which only contains the trait](https://crates.io/crates/stable_deref_trait). This way, you can implement the trait without pulling in the rest of owning_ref.

**Comment by Storyyeller** [comment]
P.S. There is the question of whether to bump version after doing this or not. It is technically a breaking change if there is someone who is both depending on parking_lot 0.4 AND specifically depending on owning_ref 0.3.0-0.3.2. However, this seems very unlikely, especially since parking_lot 0.4 was only released two days ago. I went through all the dependencies listed on crates.io, and there isn't a single dependency on parking_lot 0.4 yet.

**Comment by Amanieu** [comment]
We actually export some [typedefs](https://github.com/Amanieu/parking_lot/blob/master/src/lib.rs#L45) for `OwningRef`, which means we still need to import the `owning_ref` crate. It shouldn't make much of a difference in practice since `owning_ref` re-exports the traits from `stable_deref_trait` anyways.
