### ISSUE TITLE
Adding Windows 8+ "futex" support to parking_lot_core

### ISSUE THREAD

**Issue by Popog** [Amanieu/parking_lot#26]
Is there any interest in using [WaitOnAddress](https://msdn.microsoft.com/en-us/library/windows/desktop/hh706898(v=vs.85).aspx) / [WakeByAddressSingle](https://msdn.microsoft.com/en-us/library/windows/desktop/hh706900(v=vs.85).aspx) for Windows clients which support it (Windows 8+)?

**Comment by Amanieu** [comment]
I would be happy to accept a pull request for it. The implementation should roughly resemble the futex-based one for Linux.

I don't have any plans to implement it myself since there aren't that many advantages over the current implementation which uses NT keyed events. Especially considering that the keyed event implementation will still need to be kept to maintain compatibility with older Windows versions (keyed events were introduced in Windows XP).

**Comment by Amanieu** [comment]
Implemented in `parking_lot_core` 0.2.1.
