### ISSUE TITLE
UnwindSafe + RefUnwindSafe

### ISSUE THREAD

**Issue by ayoshi** [Amanieu/parking_lot#32]
Hi,
I apologize in advance for a question which might seem basic:

The standard library `Mutex` type implements UnwindSafe + RefUnwindSafe:

```
impl<T: ?Sized> UnwindSafe for Mutex<T>
impl<T: ?Sized> RefUnwindSafe for Mutex<T>
```
However, the implementation in a `parking_lot` doesn't.

The understanding of both implementations currently a bit out of my depth, but would it be practical (or even possible, for that matter) to lift those restrictions (implement the traits) for `parking_lot::Mutex`?

I encountered this problem, when the library I was writing against bumped it's major API to require those trait bounds, and my code was already using the `parking_lot`.

**Comment by Amanieu** [comment]
We don't implement these traits because the `parking_lot` mutex implementation does not support poisoning. This is intentional since it allows the API to be a lot simpler and it also avoids performance issues with thread-local storage accesses.

Since the lock doesn't get poisoned by unwinding, we can't claim to be unwind-safe. However you can avoid the need for this trait by using [AssertUnwindSafe](https://doc.rust-lang.org/std/panic/struct.AssertUnwindSafe.html) from the standard library.
