### ISSUE TITLE
No unwrap() function in MutexGuard

### ISSUE THREAD

**Issue by vlovich** [Amanieu/parking_lot#56]
`std::sync::MutexGuard` has an `unwrap` function that returns the contents of the mutex mutably.  The lack of this in parking_lot makes it hard to just test it as a drop-in replacement for std::sync::mutex.

**Comment by Amanieu** [comment]
`std::sync::MutexGuard` doesn't have an `unwrap` function. What happens is that `std::sync::Mutex::lock` returns a `Result<MutexGuard>`, which is then unwrapped. `parking_lot::Mutex::lock` returns a `MutexGuard` directly since locking never fails. This is by design.

**Comment by cameronelliott** [comment]
Sorry for the comment on the closed issue, but I do think a dummy 'unwrap()' would really simplify life for those
experimenting, but which haven't yet committed to parking_lot.

**Comment by cameronelliott** [comment]
@Amanieu 
One last think, and I hope this is useful info! 😅 

I tried out both `parking_lot` and `no_deadlocks` to diagnose a re-entrancy issue.
In my case, it's 3rd party code which I'm working with, so commiting removals of `.unwrap()`,  is kind of an issue
(when moving to parking_lot for deadlock diagnosis)

Also, the `no_deadlocks` reports *both* stack traces for where a lock was first taken, and then where it was re-entered.
Which is a nice improvement over just the deadlock-stacktrace.
(maybe it's not feasible for PL to keep trace of all the stack traces for performance reasons...)
I hope the feedback about ideas is useful.

https://crates.io/crates/no_deadlocks

**Comment by faern** [comment]
How about behind a feature? Like 'prototyping' or something. And mention it in some "converting from std"-section of the docs

**Comment by notgull** [comment]
I really do think there should be a crate that conditionally wraps around either `std::sync` mutexes or `parking_lot` mutexes based on a feature flag. It would ease this concern significantly.

**Comment by Amanieu** [comment]
I do like the idea of putting this behind a feature flag. This would remove the need for `#[deprecated]`.

**Comment by faern** [comment]
Testing is one thing. But it's important to remember that migrating and using this no-op `unwrap` method is not keeping the exact same behavior. The poisoning is lost, and this makes a difference in how the program behaves. I'm actually migrating some projects back to the standard library locks, because I want the poisoning functionality. The developer needs to be aware of this and decide what they need for their program. I'm just saying migration should not be so smooth that the developer misses this aspect.

> I do like the idea of putting this behind a feature flag. This would remove the need for #[deprecated].

I think it should still issue a warning, even when behind a feature flag. Otherwise I'm afraid there will be too much production code simply having the feature flag on and being to lazy to remove the unwrapping.

If we go ahead with this, don't forget to also add `expect`. I bet that's also widely used.
