### ISSUE TITLE
Support Condvar in deadlock_detection

### ISSUE THREAD

**Issue by ordian** [Amanieu/parking_lot#87]
Thanks for your work on `parking_lot`, @Amanieu! [Parity ethereum client](https://github.com/paritytech/parity-ethereum) uses this crate a lot. Unfortunately Rust type system doesn't protect us from deadlocks, so t would be very helpful if you could add support for `Condvar`s in deadlock detection. Do you think it's possible? cc @arthurprs

**Comment by arthurprs** [comment]
There is at least partial support for it already as deadlocks on the wait mutex are detected.

Can you provide examples of deadlocks that are not detected?

**Comment by Amanieu** [comment]
The deadlock detector works by looking for cycles in a graph of threads waiting for each other. This works for mutexes because we know which thread is responsible for "waking up" other threads when unlocking a mutex: it's the same thread that locked the mutex (since `MutexGuard` is not `Send`).

This doesn't work for `Condvar` because we (as in `parking_lot`) don't know which thread is supposed to signal a `Condvar` to wake up threads that are waiting on it. We can't be sure that a deadlock has occurred because some other thread may come in and signal the `Condvar`, which will unblock execution.

**Comment by ordian** [comment]
@arthurprs this kind of deadlock:
```rust
fn thread1(mutex: &Mutex<T>, cond: &Condvar) {
    // locks first
    let mut lock = mutex.lock();
    cond.wait(&mut lock); // thread2 is supposed to unlock it
}
fn thread2(mutex: &Mutex<T>, cond: &Condvar) {
    if rand::random() {
        // deadlock here
        display_info(mutex);
    }
    cond.notify_one();
}
fn display_info(mutex: &Mutex<T>) {
    mutex.lock(); // <--- blocks
    // ... 
}
```

@Amanieu Thanks for the explanation, that makes sense. I understand that this problem may not have an exact general solution. But can we somehow track all `notify` calls at compile time and detect if all threads, that could potentially signal the `Condvar` are locked? 
If that sounds impossible, feel free to close this issue.

**Comment by Amanieu** [comment]
Your example doesn't actually have a deadlock since `Condvar::wait` will unlock the mutex while the thread is waiting on the `Condvar`.

Regardless, I don't think there is anything that we can do about this issue since there isn't enough information at the `parking_lot` level to determine whether or not a deadlock has occurred. I'm going to close this issue for now, unless someone comes up with an algorithm for finding `Condvar`-related deadlocks.

**Comment by ordian** [comment]
(I've updated the example) Just an idea: track all `notify` and `wait` calls (with https://github.com/mmastrac/rust-ctor or https://github.com/dtolnay/inventory?) and detect if all threads, that could notify, are locked.
